services:
  python-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: python-app
    ports:
      - "8000:8000"
      - "8888:8888"
      - "8889:8889"
      - "8890:8890"
    volumes:
      - .:/app
    environment:
      QDRANT_HOST: http://qdrant:6333
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      POSTGRES_HOST: postgres
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - app-net

  streamlit-app:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    container_name: streamlit-app
    command: sh -c "uv run streamlit run frontend/app.py --server.port=8501 --server.address=0.0.0.0"
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    environment:
      BACKEND_URL: http://python-app:8000/question
    networks:
      - app-net

networks:
  app-net:
    external: true