global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "flask-app"
    static_configs:
      - targets: ["python-app:8000"]

  - job_name: "postgres"
    static_configs:
      - targets: ["postgres-exporter:9187"]

  - job_name: "qdrant"
    static_configs:
      - targets: ["qdrant:6333"]