services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  python-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: python-app
    ports:
      - "8000:8000"
      - "8888:8888"
      - "8889:8889"
      - "8890:8890"
    volumes:
      - .:/app
    depends_on:
      - qdrant
      - postgres
    environment:
      QDRANT_HOST: http://qdrant:6333
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./qdrant_storage:/qdrant/storage:z

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  streamlit-app:
    build:
      context: .
      dockerfile: Dockerfile.streamlit   # <- separate Dockerfile for Streamlit
    container_name: streamlit-app
    command: sh -c "uv run streamlit run frontend/app.py --server.port=8501 --server.address=0.0.0.0"
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    depends_on:
      - python-app
    environment:
      BACKEND_URL: http://python-app:8000/question

volumes:
  postgres_data:
  pgadmin_data: